name: Build the LaTeX resume

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: resume.tex
      - name: Set current date as env variable
        run: echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.date_now }}"
          draft: true
          title: "Release ${{ env.date_now }}"
          files: |
            resume.pdf
